# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fabian Hertwig's Blog
email:
description: >- # this means to ignore newlines until "baseurl:"
  I am a Machine Learning Engineer and write about Machine Learning related topics.
twitter_username: FabianHertwig
github_username: FabianHertwig
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Fabian Hertwig"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I am a Machine Learning Engineer working at MaibornWolff GmbH in Munich."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://fabianhertwig.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/FabianHertwig"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/FabianHertwig"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/FabianHertwig"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/FabianHertwig"
    - label: "Privacy Notice"
      url: /privacy/
    - label: "Impressum"
      url: /impressum/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

after_footer_scripts:
  - /assets/js/cookie-consent.js
#  - /assets/js/google-analytics.js

url: "https.fabian.hertwig.github.io"
baseurl: ""
consented_google_analytics: "G-N76K892CTB"

repository: FabianHertwig/FabianHertwig.github.io
comments:
  # 'disqus' or 'utterances' are available
  provider:            giscus

# You must install giscus github app before use.(https://github.com/apps/giscus)
# Make sure all variables are set properly. Check below link for detail.
# https://giscus.vercel.app/
giscus:
  repo:                "FabianHertwig/FabianHertwig.github.io"
  repo-id:             "R_kgDOGQ92mA"
  category:            "Comments"
  category-id:         "DIC_kwDOGQ92mM4CAivM"
  mapping:             "pathname"
  reaction-enabled:    "1"
  emit-metadata:       "0"
  theme:               "light"
  lang:                "en"
  crossorigin:         "anonymous"